config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :booking_types
  resources :bookings
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users

  authenticated :user do
    root to: "home#dashboard", as: :authenticated_root
  end

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_person_name
  belongs_to :booking_type
  has_rich_text :notes
end

app/models/booking_type.rb
class BookingType < ApplicationRecord
  belongs_to :user
  has_rich_text :description
  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :booking_types
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/booking_types_controller.rb
class BookingTypesController < ApplicationController
  before_action :set_booking_type, only: %i[ show edit update destroy ]

  # GET /booking_types or /booking_types.json
  def index
    @booking_types = BookingType.all
  end

  # GET /booking_types/1 or /booking_types/1.json
  def show
  end

  # GET /booking_types/new
  def new
    @booking_type = BookingType.new
  end

  # GET /booking_types/1/edit
  def edit
  end

  # POST /booking_types or /booking_types.json
  def create
    @booking_type = BookingType.new(booking_type_params)

    respond_to do |format|
      if @booking_type.save
        format.html { redirect_to booking_type_url(@booking_type), notice: "Booking type was successfully created." }
        format.json { render :show, status: :created, location: @booking_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booking_types/1 or /booking_types/1.json
  def update
    respond_to do |format|
      if @booking_type.update(booking_type_params)
        format.html { redirect_to booking_type_url(@booking_type), notice: "Booking type was successfully updated." }
        format.json { render :show, status: :ok, location: @booking_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booking_types/1 or /booking_types/1.json
  def destroy
    @booking_type.destroy

    respond_to do |format|
      format.html { redirect_to booking_types_url, notice: "Booking type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking_type
      @booking_type = BookingType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_type_params
      params.require(:booking_type).permit(:name, :location, :description, :color, :duration, :payment_required, :price, :user_id)
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:status, :first_name, :last_name, :email, :start_at, :end_at)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def dashboard

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_classes(flash_type)
    flash_base = "px-2 py-4 mx-auto font-sans font-medium text-center text-white"
    {
      notice: "bg-indigo-600 #{flash_base}",
      error:  "bg-red-600 #{flash_base}",
      alert: "bg-red-600 #{flash_base}"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def nav_classes
    ["devise/registrations", "devise/sessions", "devise/confirmations", "devise/passwords", "devise/unlocks"].include?(params[:controller]) ? "hidden" : nil
  end

  def label_class(options={})
    "block mb-1 font-normal leading-normal #{options[:extended_classes]}"
  end

  def input_class(options={})
    "rounded border border-gray-300 block w-full focus:outline-none focus:border-gray-400 outline-none focus-within:outline-none focus:ring-2 focus:ring-gray-200 #{options[:extended_classes]}"
  end

  def checkbox_class(options={})
    "rounded border-gray-300 border focus:ring-2 focus:ring-gray-200 text-blue-500 mr-1 #{options[:extended_classes]}"
  end

  def link_class(options={})
    "text-gray-700 underline hover:no-underline hover:text-gray-800 block #{options[:extended_classes]}"
  end

  def button_class(options={})
    variant = options[:variant]
    theme = options[:theme]

    style_button(variant, theme_button(theme))
  end

  def theme_button(theme)
    themes = {
      primary: "primary",
      secondary: "secondary",
      transparent: "transparent",
      dark: "dark"
    }

    case theme
    when themes[:primary]
      "bg-indigo-600 hover:bg-indigo-700 text-white"
    when themes[:secondary]
      "bg-teal-600 hover:bg-teal-700 text-white"
    when themes[:transparent]
      "bg-transparent hover:bg-gray-100 text-gray-700"
    when themes[:dark]
      "bg-gray-800 text-white shadow-sm hover:bg-gray-900"
    else
      "bg-white border border-gray-300 shadow-sm hover:bg-gray-100"
    end
  end

  def style_button(variant, theme)
    base = "rounded text-center font-sans font-normal outline-none leading-normal cursor-pointer transition ease-in-out duration-200 font-medium"

    case variant
    when "large"
      "px-5 py-4 text-lg #{base} #{theme}"
    when "small"
      "py-2 px-4 text-sm #{base} #{theme}"
    when "expanded"
      "p-3 w-full block #{base} #{theme}"
    else
      "px-5 py-2 text-base #{base} #{theme}"
    end
  end
end

app/helpers/booking_types_helper.rb
module BookingTypesHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/booking_types/_booking_type.html.erb
<div id="<%= dom_id booking_type %>">
  <p>
    <strong>Name:</strong>
    <%= booking_type.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= booking_type.location %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= booking_type.description %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= booking_type.color %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= booking_type.duration %>
  </p>

  <p>
    <strong>Payment required:</strong>
    <%= booking_type.payment_required %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= booking_type.price %>
  </p>

  <p>
    <strong>User:</strong>
    <%= booking_type.user_id %>
  </p>

</div>

app/views/booking_types/_form.html.erb
<%= form_with(model: booking_type) do |form| %>
<% if booking_type.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(booking_type.errors.count, "error") %> prohibited this booking_type from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% booking_type.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :name, class: label_class %>
          <%= form.text_field :name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :location, class: label_class %>
          <%= form.text_field :location, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :description, class: label_class %>
          <%= form.rich_text_area :description, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :color, class: label_class %>
          <%= form.text_field :color, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :duration, class: label_class %>
          <%= form.number_field :duration, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :payment_required, class: label_class %>
          <%= form.check_box :payment_required, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :price, class: label_class %>
          <%= form.number_field :price, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :user_id, class: label_class %>
          <%= form.text_field :user_id, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if booking_type.persisted? %>
<%= link_to "Cancel", booking_type, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", booking_types_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/booking_types/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit booking_type</h1>
    <% if @booking_type.persisted? %>
    <%= button_to 'Destroy', @booking_type, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', booking_type: @booking_type %>
</div>

app/views/booking_types/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Booking_types</h1>

    <%= link_to new_booking_type_path, class: button_class(theme: "primary") do %>
    Add New Booking type
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Location</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Description</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Color</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Duration</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Payment required</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Price</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">User</th>
                
      </tr>
    </thead>

    <tbody>
      <% @booking_types.each do |booking_type| %>
      <%= content_tag :tr, id: dom_id(booking_type), class: dom_class(booking_type) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to booking_type.name, booking_type %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.location %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.description %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.color %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.duration %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.payment_required %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.price %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking_type.user %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/booking_types/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New booking_type</h1>

  <%= render 'form', booking_type: @booking_type %>
</div>

app/views/booking_types/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Booking_type</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to booking_types_path, class: button_class(theme: "transparent") do %>
      All Booking_types
      <% end %>
      <%= link_to edit_booking_type_path(@booking_type), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Name:</p>
        <p><%= @booking_type.name %></p>
      </li>
      <li>
        <p class="font-semibold">Location:</p>
        <p><%= @booking_type.location %></p>
      </li>
      <li>
        <p class="font-semibold">Description:</p>
        <p><%= @booking_type.description %></p>
      </li>
      <li>
        <p class="font-semibold">Color:</p>
        <p><%= @booking_type.color %></p>
      </li>
      <li>
        <p class="font-semibold">Duration:</p>
        <p><%= @booking_type.duration %></p>
      </li>
      <li>
        <p class="font-semibold">Payment required:</p>
        <p><%= @booking_type.payment_required %></p>
      </li>
      <li>
        <p class="font-semibold">Price:</p>
        <p><%= @booking_type.price %></p>
      </li>
      <li>
        <p class="font-semibold">User:</p>
        <p><%= @booking_type.user %></p>
      </li>
  </ul>
</div>

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Status:</strong>
    <%= booking.status %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= booking.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= booking.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= booking.email %>
  </p>

  <p>
    <strong>Start at:</strong>
    <%= booking.start_at %>
  </p>

  <p>
    <strong>End at:</strong>
    <%= booking.end_at %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
<% if booking.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% booking.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :status, class: label_class %>
          <%= form.number_field :status, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :first_name, class: label_class %>
          <%= form.text_field :first_name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :last_name, class: label_class %>
          <%= form.text_field :last_name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :email, class: label_class %>
          <%= form.text_field :email, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :start_at, class: label_class %>
          <%= form.datetime_field :start_at, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :end_at, class: label_class %>
          <%= form.datetime_field :end_at, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if booking.persisted? %>
<%= link_to "Cancel", booking, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", bookings_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/bookings/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit booking</h1>
    <% if @booking.persisted? %>
    <%= button_to 'Destroy', @booking, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', booking: @booking %>
</div>

app/views/bookings/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Bookings</h1>

    <%= link_to new_booking_path, class: button_class(theme: "primary") do %>
    Add New Booking
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Status</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">First name</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Last name</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Email</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Start at</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">End at</th>
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @bookings.each do |booking| %>
      <%= content_tag :tr, id: dom_id(booking), class: dom_class(booking) do %>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking.status %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking.first_name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking.last_name %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking.email %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking.start_at %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= booking.end_at %></td>
      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', booking %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/bookings/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New booking</h1>

  <%= render 'form', booking: @booking %>
</div>

app/views/bookings/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Booking</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to bookings_path, class: button_class(theme: "transparent") do %>
      All Bookings
      <% end %>
      <%= link_to edit_booking_path(@booking), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Status:</p>
        <p><%= @booking.status %></p>
      </li>
      <li>
        <p class="font-semibold">First name:</p>
        <p><%= @booking.first_name %></p>
      </li>
      <li>
        <p class="font-semibold">Last name:</p>
        <p><%= @booking.last_name %></p>
      </li>
      <li>
        <p class="font-semibold">Email:</p>
        <p><%= @booking.email %></p>
      </li>
      <li>
        <p class="font-semibold">Start at:</p>
        <p><%= @booking.start_at %></p>
      </li>
      <li>
        <p class="font-semibold">End at:</p>
        <p><%= @booking.end_at %></p>
      </li>
  </ul>
</div>

app/views/home/dashboard.html.erb
<h1>Dashboard</h1>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full antialiased">
  <%= render "shared/head" %>

  <body class="font-sans font-normal leading-normal text-gray-800 bg-white flex flex-col min-h-screen ">

    <header>
      <%= render "shared/flash_notice" %>
      <%= render "shared/navbar" %>
    </header>

    <main class="flex-grow">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
  </body>
</html>

app/views/shared/_flash_notice.html.erb
<% flash.each do |type, message| %>
  <div class="<%= flash_classes(type) %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title>
    <%= content_for?(:title) ? yield(:title) : "Kickoff Tailwind" %>
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "application", defer: true %>
  <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
</head>